version: '3.4'

services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server"]

  community.extensions.caching.sample:
    image: ${DOCKER_REGISTRY}communityextensionscachingsample
    build:
      context: .
      dockerfile: Community.Extensions.Caching.Sample/Dockerfile
